javascript exercise
juanazadian/onboarding_eW pull request #7
Opened 2021-07-22 19:09 UTC by juanazadian

Simple web implemented for the javascript exercise. 
The style was done with bootstrap but the modal style was customized separately.

2021-07-22 20:17 UTC, jpbalarini requested changes
Left some comments. 
Also, let's add boostrap 5 to the root of the project structure so we don't have to import it in each part (you could remove boostrap 4 from the previous parts)

2021-07-22 20:17 UTC, jpbalarini commented on js/ex4js.html
> +
remove empty new line

2021-07-22 20:17 UTC, jpbalarini commented on js/style.scss
> +.modal-juan {
haha, `juan` looks like a non descriptive class. Let's use something like `custom-modal` or something similar

2021-07-22 20:17 UTC, jpbalarini commented on js/scripts.js
> +optim.onclick = function(){
let's improve this. You could use an Array sort (with a custom sort function) to generate a sorted list and then iterate that list  and use the `appendChild`  function.

2021-07-23 19:18 UTC, juanazadian commented
![image](https://user-images.githubusercontent.com/79284152/126830845-83a14486-2225-4a83-9f33-aa329ebcbc6c.png)

2021-07-23 19:24 UTC, merged