ex4jquery done
juanazadian/onboarding_eW pull request #9
Opened 2021-07-26 16:09 UTC by juanazadian

javascript exercise now implemented using jquery library.
       html located under js folder (ex4jquery.html) 
       script also located under js folder (ex4jquery.js)
![image](https://user-images.githubusercontent.com/79284152/127022275-39c872ce-84d5-4bbc-af9b-35a2ab55ff10.png)

2021-07-26 16:35 UTC, jpbalarini requested changes

2021-07-26 16:35 UTC, jpbalarini commented on js/ex4jquery.js
> +    $("#modal").css("display","block");
use a space after a `,`

2021-07-26 16:35 UTC, jpbalarini commented on js/ex4jquery.js
> +    $("#modal").css("display","block");
you can use .show() or .toogle()

2021-07-26 16:35 UTC, jpbalarini commented on js/ex4jquery.js
> +    $("table tbody").append(newrow)
missing `;`

2021-07-26 16:35 UTC, jpbalarini commented on js/ex4jquery.js
> +    $("#modal").css("display","none");
use .hide()

2021-07-26 16:35 UTC, jpbalarini commented on js/ex4jquery.js
> +    acc = 0;
`let acc = 0;`

2021-07-26 16:35 UTC, jpbalarini commented on js/ex4jquery.js
> +    budget = parseInt($("#budget").text());
let budget ...

2021-07-26 16:35 UTC, jpbalarini commented on js/ex4jquery.js
> +    $("table > tbody > tr").each(function(){
missing space `function() {`

2021-07-26 16:35 UTC, jpbalarini commented on js/ex4jquery.js
> +      if (acc<=budget)
`if (acc <= budget)`

2021-07-26 16:35 UTC, jpbalarini commented on js/ex4jquery.js
> +
remove empty newline

2021-07-26 16:35 UTC, jpbalarini commented on js/ex4jquery.js
> +  function sortRows(a,b) {
`sortRows(a, b)`

2021-07-26 16:35 UTC, jpbalarini commented on js/ex4jquery.js
> +    return parseInt(a.getElementsByTagName("td")[1].innerHTML) - parseInt(b.getElementsByTagName("td")[1].innerHTML)
missing ;

2021-07-26 16:35 UTC, jpbalarini commented on js/ex4jquery.js
> +    for (i = 0; i < (sortedArray.length); i++)
it's a good practice to always add the `{}` since someone could forget to add them after adding more statements to the for

2021-07-26 16:35 UTC, jpbalarini commented on js/ex4jquery.js
> +    checkBudget()
missing `;`

2021-07-26 16:50 UTC, jpbalarini approved these changes

2021-07-27 14:29 UTC, jpbalarini approved these changes

2021-07-27 14:29 UTC, jpbalarini commented on js/ex4jquery.js
> +  while ( i-- ) {
should be `while (i--) {`

2021-07-27 14:29 UTC, jpbalarini commented on js/ex4jquery.js
> +  let wishlistItemsJSON = localStorage.getItem("wishlistItems")
; missing

2021-07-27 14:35 UTC, merged

2021-07-27 14:35 UTC, juanazadian commented
closed